name: Build Yocto

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  compile:
    strategy:
      fail-fast: true
      matrix:
        machine:
          - qcm6490-idp
          - qcs6490-rb3gen2-core-kit
          - sa8775p-ride-sx
    runs-on: [self-hosted, x86]
    name: ${{ matrix.machine }}/poky/systemd
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Kas build
        run: |
          export DL_DIR=/srv/gh-runners/quic-yocto/downloads
          export SSTATE_DIR=/srv/gh-runners/quic-yocto/sstate-cache
          mkdir -p $DL_DIR
          mkdir -p $SSTATE_DIR
          mkdir build
          cd build
          kas build ../ci/${{ matrix.machine }}.yml

      - name: Publish image
        run: |
          set -x
          build_dir=/srv/gh-runners/quic-yocto/builds/${GITHUB_RUN_ID}
          mkdir -p $build_dir
          img_dir=$build_dir/${{ matrix.machine }}
          [ -d $img_dir ] && rm -rf $img_dir
          mv build/deploy/images $img_dir

          echo Image available at: https://quic-yocto-fileserver-1029608027416.us-central1.run.app/${GITHUB_RUN_ID}/${{ matrix.machine }}
